"""Fix admin_id and target_user_id to BigInteger

Revision ID: 1cf79712b871
Revises: 4c0d670160a4
Create Date: 2025-11-17 15:50:46.248366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf79712b871'
down_revision: Union[str, Sequence[str], None] = '4c0d670160a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_logs', 'admin_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Admin telegram ID',
               existing_nullable=False)
    op.alter_column('admin_logs', 'target_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='Target user ID (if applicable)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_logs', 'target_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Target user ID (if applicable)',
               existing_nullable=True)
    op.alter_column('admin_logs', 'admin_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_comment='Admin telegram ID',
               existing_nullable=False)
    # ### end Alembic commands ###
