"""add_supervisor_tables

Revision ID: 25b05c9afc92
Revises: 7444448bf4b0
Create Date: 2025-12-16 20:46:18.646336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b05c9afc92'
down_revision: Union[str, Sequence[str], None] = '7444448bf4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=False, comment='Unique trade ID from trading bot'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='User telegram_id'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Trading pair (e.g., BTCUSDT)'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='Timeframe (1h, 4h, 1d)'),
    sa.Column('side', sa.String(length=10), nullable=False, comment='Position side (Long/Short)'),
    sa.Column('bias', sa.String(length=20), nullable=False, comment='Market bias (bull/bear/range)'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Scenario confidence 0-1'),
    sa.Column('entry_zone_low', sa.Float(), nullable=False, comment='Entry zone low price'),
    sa.Column('entry_zone_high', sa.Float(), nullable=False, comment='Entry zone high price'),
    sa.Column('stop_loss', sa.Float(), nullable=False, comment='Stop loss price'),
    sa.Column('invalidation_price', sa.Float(), nullable=False, comment='Price that invalidates scenario (KEY!)'),
    sa.Column('take_profits_json', sa.Text(), nullable=False, comment='JSON array of TP levels [{price, pct, rr}, ...]'),
    sa.Column('conditions_json', sa.Text(), nullable=True, comment='JSON array of validity conditions'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False, comment='Scenario valid until this time'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='Scenario source (syntra/manual)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is this scenario still being supervised'),
    sa.Column('deactivated_reason', sa.String(length=100), nullable=True, comment='Reason for deactivation'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_snapshots_trade_id'), 'scenario_snapshots', ['trade_id'], unique=True)
    op.create_index(op.f('ix_scenario_snapshots_user_id'), 'scenario_snapshots', ['user_id'], unique=False)
    op.create_table('supervisor_advices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('market_summary', sa.Text(), nullable=False, comment='1-2 line market summary'),
    sa.Column('scenario_valid', sa.Boolean(), nullable=False, comment='Is scenario still valid'),
    sa.Column('time_valid_left_min', sa.Integer(), nullable=False, comment='Minutes left until scenario expires'),
    sa.Column('risk_state', sa.String(length=20), nullable=False, comment='Risk state (safe/medium/high/critical)'),
    sa.Column('price_at_creation', sa.Float(), nullable=False, comment='Mark price when advice was created'),
    sa.Column('recommendations_json', sa.Text(), nullable=False, comment='JSON array of recommendations'),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True, comment="Don't create new advice until this time"),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True, comment='Telegram message ID for updating'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When this advice expires'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisor_advices_scenario_id'), 'supervisor_advices', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_supervisor_advices_trade_id'), 'supervisor_advices', ['trade_id'], unique=False)
    op.create_index(op.f('ix_supervisor_advices_user_id'), 'supervisor_advices', ['user_id'], unique=False)
    op.create_table('supervisor_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('advice_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.String(length=50), nullable=False, comment='Unique action ID within advice'),
    sa.Column('action_type', sa.String(length=30), nullable=False, comment='Type of action (move_sl, take_partial, etc.)'),
    sa.Column('params_json', sa.Text(), nullable=False, comment='JSON params of the action'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending/applied/rejected/expired'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_result', sa.Text(), nullable=True, comment='JSON result from execution (order_id, error, etc.)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['advice_id'], ['supervisor_advices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supervisor_actions_advice_id'), 'supervisor_actions', ['advice_id'], unique=False)
    op.create_index(op.f('ix_supervisor_actions_trade_id'), 'supervisor_actions', ['trade_id'], unique=False)
    op.create_index(op.f('ix_supervisor_actions_user_id'), 'supervisor_actions', ['user_id'], unique=False)
    op.drop_constraint(op.f('points_balances_user_id_key'), 'points_balances', type_='unique')
    op.drop_constraint(op.f('points_levels_level_key'), 'points_levels', type_='unique')
    op.drop_constraint(op.f('points_transactions_transaction_id_key'), 'points_transactions', type_='unique')
    op.alter_column('users', 'startapp_param',
               existing_type=sa.VARCHAR(length=255),
               comment='Startapp parameter from deep link (e.g., web3moves, telegram_channel)',
               existing_nullable=True)
    op.drop_index(op.f('idx_users_startapp_param'), table_name='users')
    op.create_index(op.f('ix_users_startapp_param'), 'users', ['startapp_param'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_startapp_param'), table_name='users')
    op.create_index(op.f('idx_users_startapp_param'), 'users', ['startapp_param'], unique=False)
    op.alter_column('users', 'startapp_param',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Startapp parameter from deep link (e.g., web3moves, telegram_channel)',
               existing_nullable=True)
    op.create_unique_constraint(op.f('points_transactions_transaction_id_key'), 'points_transactions', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('points_levels_level_key'), 'points_levels', ['level'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('points_balances_user_id_key'), 'points_balances', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_supervisor_actions_user_id'), table_name='supervisor_actions')
    op.drop_index(op.f('ix_supervisor_actions_trade_id'), table_name='supervisor_actions')
    op.drop_index(op.f('ix_supervisor_actions_advice_id'), table_name='supervisor_actions')
    op.drop_table('supervisor_actions')
    op.drop_index(op.f('ix_supervisor_advices_user_id'), table_name='supervisor_advices')
    op.drop_index(op.f('ix_supervisor_advices_trade_id'), table_name='supervisor_advices')
    op.drop_index(op.f('ix_supervisor_advices_scenario_id'), table_name='supervisor_advices')
    op.drop_table('supervisor_advices')
    op.drop_index(op.f('ix_scenario_snapshots_user_id'), table_name='scenario_snapshots')
    op.drop_index(op.f('ix_scenario_snapshots_trade_id'), table_name='scenario_snapshots')
    op.drop_table('scenario_snapshots')
    # ### end Alembic commands ###
