"""Initial database schema

Revision ID: 2e5903c1536e
Revises: 
Create Date: 2025-11-17 02:04:14.916065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5903c1536e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False, comment='Admin telegram ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Action performed (e.g., reset_limits, ban_user)'),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True, comment='Target user ID (if applicable)'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Action timestamp'),
    sa.Column('details', sa.Text(), nullable=True, comment='Additional details (JSON or text)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Was the action successful'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_action'), 'admin_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_logs_admin_id'), 'admin_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_target_user_id'), 'admin_logs', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_timestamp'), 'admin_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram user ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Telegram username (without @)'),
    sa.Column('first_name', sa.String(length=255), nullable=True, comment='User first name'),
    sa.Column('last_name', sa.String(length=255), nullable=True, comment='User last name'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='User registration timestamp'),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False, comment='Is user subscribed to required channel'),
    sa.Column('last_activity', sa.DateTime(), nullable=False, comment='Last user activity timestamp'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Is user an admin'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('chat_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='User ID (foreign key)'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Message role: user, assistant, system'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Message timestamp'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='Tokens used (for AI responses)'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='AI model used (gpt-4o, gpt-4o-mini, etc.)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_timestamp'), 'chat_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('cost_tracking',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='User ID (foreign key)'),
    sa.Column('service', sa.String(length=50), nullable=False, comment='Service name: openai, together, coingecko, etc.'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='Specific model used'),
    sa.Column('tokens', sa.Integer(), nullable=False, comment='Tokens used (if applicable)'),
    sa.Column('cost', sa.Float(), nullable=False, comment='Calculated cost in USD'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Timestamp of the request'),
    sa.Column('request_type', sa.String(length=100), nullable=True, comment='Type of request: chat, vision, price, etc.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_tracking_service'), 'cost_tracking', ['service'], unique=False)
    op.create_index(op.f('ix_cost_tracking_timestamp'), 'cost_tracking', ['timestamp'], unique=False)
    op.create_index(op.f('ix_cost_tracking_user_id'), 'cost_tracking', ['user_id'], unique=False)
    op.create_table('request_limits',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='User ID (foreign key)'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date for this limit count'),
    sa.Column('count', sa.Integer(), nullable=False, comment='Number of requests made today'),
    sa.Column('limit', sa.Integer(), nullable=False, comment='Request limit (default 5)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uix_user_date')
    )
    op.create_index(op.f('ix_request_limits_date'), 'request_limits', ['date'], unique=False)
    op.create_index(op.f('ix_request_limits_user_id'), 'request_limits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_limits_user_id'), table_name='request_limits')
    op.drop_index(op.f('ix_request_limits_date'), table_name='request_limits')
    op.drop_table('request_limits')
    op.drop_index(op.f('ix_cost_tracking_user_id'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_timestamp'), table_name='cost_tracking')
    op.drop_index(op.f('ix_cost_tracking_service'), table_name='cost_tracking')
    op.drop_table('cost_tracking')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_timestamp'), table_name='chat_history')
    op.drop_table('chat_history')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_admin_logs_timestamp'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_target_user_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_admin_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_action'), table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
