"""add_social_tasks_system

Revision ID: 3378721a34ca
Revises: 9925edd99a92
Create Date: 2025-12-03 17:15:42.379821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3378721a34ca'
down_revision: Union[str, Sequence[str], None] = '9925edd99a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False, comment='Task title in Russian'),
    sa.Column('title_en', sa.String(length=255), nullable=False, comment='Task title in English'),
    sa.Column('description_ru', sa.Text(), nullable=True, comment='Task description in Russian'),
    sa.Column('description_en', sa.Text(), nullable=True, comment='Task description in English'),
    sa.Column('icon', sa.String(length=10), nullable=False, comment='Emoji icon for task'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='Type of task (TaskType enum)'),
    sa.Column('telegram_channel_id', sa.String(length=100), nullable=True, comment='Telegram channel/chat ID (@username or -100xxx)'),
    sa.Column('telegram_channel_url', sa.String(length=255), nullable=True, comment='Telegram channel/chat URL for redirect'),
    sa.Column('twitter_target_username', sa.String(length=100), nullable=True, comment='Twitter username to follow (without @)'),
    sa.Column('verification_type', sa.String(length=30), nullable=False, comment='How to verify completion (VerificationType enum)'),
    sa.Column('reward_points', sa.Integer(), nullable=False, comment='Points awarded for completion'),
    sa.Column('unsubscribe_penalty', sa.Integer(), nullable=False, comment='Penalty points if user unsubscribes'),
    sa.Column('max_completions', sa.Integer(), nullable=True, comment='Maximum total completions allowed (null = unlimited)'),
    sa.Column('current_completions', sa.Integer(), nullable=False, comment='Current number of completions'),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False, comment='Can user complete this task multiple times'),
    sa.Column('repeat_interval_hours', sa.Integer(), nullable=True, comment='Hours between repeated completions'),
    sa.Column('requires_premium', sa.Boolean(), nullable=False, comment='Requires premium subscription'),
    sa.Column('min_level', sa.Integer(), nullable=False, comment='Minimum user level required'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Display priority (higher = shown first)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Task status (TaskStatus enum)'),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True, comment='When task becomes available'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When task expires'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='Admin telegram_id who created task'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_tasks_priority'), 'social_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_social_tasks_status'), 'social_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_social_tasks_task_type'), 'social_tasks', ['task_type'], unique=False)
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='Task ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Completion status (TaskCompletionStatus enum)'),
    sa.Column('points_awarded', sa.Integer(), nullable=False, comment='Points awarded for this completion'),
    sa.Column('points_transaction_id', sa.Integer(), nullable=True, comment='Reference to points transaction'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True, comment='When verification was completed'),
    sa.Column('verification_data', sa.Text(), nullable=True, comment='JSON data from verification (chat_member info, etc.)'),
    sa.Column('completion_count', sa.Integer(), nullable=False, comment='Which completion number this is (for repeatable tasks)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='When user started the task'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When task was completed'),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True, comment='URL to uploaded screenshot'),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True, comment='Admin telegram_id who reviewed'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='When admin reviewed'),
    sa.Column('review_notes', sa.Text(), nullable=True, comment='Admin notes on review'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When reward was revoked (user unsubscribed)'),
    sa.Column('penalty_applied', sa.Integer(), nullable=False, comment='Penalty points applied on revocation'),
    sa.Column('penalty_transaction_id', sa.Integer(), nullable=True, comment='Reference to penalty transaction'),
    sa.Column('last_recheck_at', sa.DateTime(timezone=True), nullable=True, comment='Last subscription recheck time'),
    sa.ForeignKeyConstraint(['penalty_transaction_id'], ['points_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['points_transaction_id'], ['points_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['social_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', 'completion_count', name='uq_task_user_completion')
    )
    op.create_index(op.f('ix_task_completions_status'), 'task_completions', ['status'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_completions_user_id'), 'task_completions', ['user_id'], unique=False)
    # NOTE: Removed auto-generated drop_constraint commands that would break existing indexes
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_completions_user_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_status'), table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_index(op.f('ix_social_tasks_task_type'), table_name='social_tasks')
    op.drop_index(op.f('ix_social_tasks_status'), table_name='social_tasks')
    op.drop_index(op.f('ix_social_tasks_priority'), table_name='social_tasks')
    op.drop_table('social_tasks')
    # ### end Alembic commands ###
