"""Add premium subscription system

Revision ID: 3818b6add546
Revises: 1cf79712b871
Create Date: 2025-11-17 15:53:23.470979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3818b6add546'
down_revision: Union[str, Sequence[str], None] = '1cf79712b871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID (foreign key)'),
    sa.Column('tier', sa.String(length=20), nullable=False, comment='Subscription tier: free, basic, premium, vip'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='Subscription start date'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Subscription expiration date (NULL for FREE)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Is subscription currently active'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False, comment='Auto-renew subscription'),
    sa.Column('is_trial', sa.Boolean(), nullable=False, comment='Is this a trial subscription'),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True, comment='Trial end date'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_tier'), 'subscriptions', ['tier'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID (foreign key)'),
    sa.Column('subscription_id', sa.Integer(), nullable=False, comment='Subscription ID (foreign key)'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Payment provider: telegram_stars, ton_connect, crypto_bot'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Payment status: pending, completed, failed, refunded, cancelled'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Payment amount in USD'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency: USD, STARS, TON, USDT'),
    sa.Column('tier', sa.String(length=20), nullable=False, comment='Purchased tier'),
    sa.Column('duration_months', sa.Integer(), nullable=False, comment='Subscription duration in months (1, 3, 12)'),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=True, comment='External payment ID from provider'),
    sa.Column('provider_data', sa.Text(), nullable=True, comment='Additional provider data (JSON)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Payment creation timestamp'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Payment completion timestamp'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tier'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
