"""Change DateTime columns to timezone aware

Revision ID: 4c0d670160a4
Revises: 897e74eec34d
Create Date: 2025-11-17 15:40:04.799899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c0d670160a4'
down_revision: Union[str, Sequence[str], None] = '897e74eec34d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Action timestamp',
               existing_nullable=False)
    op.alter_column('chat_history', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Message timestamp',
               existing_nullable=False)
    op.alter_column('cost_tracking', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Timestamp of the request',
               existing_nullable=False)
    op.alter_column('funding_rates', 'funding_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Funding interval timestamp',
               existing_nullable=False)
    op.alter_column('historical_prices', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Candlestick timestamp',
               existing_nullable=False)
    op.alter_column('onchain_metrics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Metric timestamp',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='User registration timestamp',
               existing_nullable=False)
    op.alter_column('users', 'last_activity',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Last user activity timestamp',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_activity',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Last user activity timestamp',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='User registration timestamp',
               existing_nullable=False)
    op.alter_column('onchain_metrics', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Metric timestamp',
               existing_nullable=False)
    op.alter_column('historical_prices', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Candlestick timestamp',
               existing_nullable=False)
    op.alter_column('funding_rates', 'funding_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Funding interval timestamp',
               existing_nullable=False)
    op.alter_column('cost_tracking', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Timestamp of the request',
               existing_nullable=False)
    op.alter_column('chat_history', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Message timestamp',
               existing_nullable=False)
    op.alter_column('admin_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Action timestamp',
               existing_nullable=False)
    # ### end Alembic commands ###
