"""add_referral_code_to_magic_links

Revision ID: 548573fe410b
Revises: 91986625f763
Create Date: 2025-11-25 10:03:00.947993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548573fe410b'
down_revision: Union[str, Sequence[str], None] = '91986625f763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magic_links', sa.Column('referral_code', sa.String(length=20), nullable=True, comment='Referral code from URL if user arrived via referral link'))
    op.drop_constraint(op.f('magic_links_token_key'), 'magic_links', type_='unique')
    op.alter_column('payments', 'subscription_id',
               existing_type=sa.INTEGER(),
               comment='Subscription ID (foreign key) - nullable until payment is completed',
               existing_comment='Subscription ID (foreign key)',
               existing_nullable=True)
    op.alter_column('referral_tiers', 'revenue_share_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_comment='Revenue share percentage (0-100)',
               existing_nullable=False)
    op.alter_column('request_limits', 'count',
               existing_type=sa.INTEGER(),
               comment='DEPRECATED: Total requests (use text_count)',
               existing_comment='Number of requests made today',
               existing_nullable=False)
    op.alter_column('request_limits', 'limit',
               existing_type=sa.INTEGER(),
               comment='DEPRECATED: Request limit (use tier-based limits)',
               existing_comment='Request limit (default 5)',
               existing_nullable=False)
    # Drop constraint only if it exists (may be created as unique index instead)
    # op.drop_constraint(op.f('ton_scanner_states_address_key'), 'ton_scanner_states', type_='unique')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               comment='Telegram user ID (nullable for web users)',
               existing_comment='Telegram user ID',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email for web registration',
               existing_comment='User email for web registration',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Username (Telegram username or display name)',
               existing_comment='Telegram username (without @)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               comment='Telegram username (without @)',
               existing_comment='Username (Telegram username or display name)',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User email for web registration',
               existing_comment='Email for web registration',
               existing_nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               comment='Telegram user ID',
               existing_comment='Telegram user ID (nullable for web users)',
               existing_nullable=True)
    # Constraint already exists as unique index from initial migration
    # op.create_unique_constraint(op.f('ton_scanner_states_address_key'), 'ton_scanner_states', ['address'], postgresql_nulls_not_distinct=False)
    op.alter_column('request_limits', 'limit',
               existing_type=sa.INTEGER(),
               comment='Request limit (default 5)',
               existing_comment='DEPRECATED: Request limit (use tier-based limits)',
               existing_nullable=False)
    op.alter_column('request_limits', 'count',
               existing_type=sa.INTEGER(),
               comment='Number of requests made today',
               existing_comment='DEPRECATED: Total requests (use text_count)',
               existing_nullable=False)
    op.alter_column('referral_tiers', 'revenue_share_percent',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_comment='Revenue share percentage (0-100)',
               existing_nullable=False)
    op.alter_column('payments', 'subscription_id',
               existing_type=sa.INTEGER(),
               comment='Subscription ID (foreign key)',
               existing_comment='Subscription ID (foreign key) - nullable until payment is completed',
               existing_nullable=True)
    op.create_unique_constraint(op.f('magic_links_token_key'), 'magic_links', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('magic_links', 'referral_code')
    # ### end Alembic commands ###
