"""add trial_start and rename trial_ends_at to trial_end

Revision ID: 630cbed7a5c1
Revises: d8f3c2e1a4b5
Create Date: 2025-11-27 15:03:36.745692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '630cbed7a5c1'
down_revision: Union[str, Sequence[str], None] = 'd8f3c2e1a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crypto_invoices', 'asset',
               existing_type=sa.VARCHAR(length=20),
               comment='Cryptocurrency (USDT, TON, BTC, ETH, etc.)',
               existing_comment='Cryptocurrency (USDT, TON, BTC, etc.)',
               existing_nullable=False)
    op.drop_index(op.f('ix_crypto_invoices_hash'), table_name='crypto_invoices')
    op.create_unique_constraint(None, 'crypto_invoices', ['hash'])

    # Add new trial columns
    op.add_column('subscriptions', sa.Column('trial_start', sa.DateTime(timezone=True), nullable=True, comment='Trial start date'))
    op.add_column('subscriptions', sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True, comment='Trial end date'))

    # Migrate existing data: copy trial_ends_at to trial_end
    op.execute('UPDATE subscriptions SET trial_end = trial_ends_at WHERE trial_ends_at IS NOT NULL')

    # Create index and drop old column
    op.create_index(op.f('ix_subscriptions_trial_end'), 'subscriptions', ['trial_end'], unique=False)
    op.drop_column('subscriptions', 'trial_ends_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('trial_ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Trial end date'))
    op.drop_index(op.f('ix_subscriptions_trial_end'), table_name='subscriptions')
    op.drop_column('subscriptions', 'trial_end')
    op.drop_column('subscriptions', 'trial_start')
    op.drop_constraint(None, 'crypto_invoices', type_='unique')
    op.create_index(op.f('ix_crypto_invoices_hash'), 'crypto_invoices', ['hash'], unique=True)
    op.alter_column('crypto_invoices', 'asset',
               existing_type=sa.VARCHAR(length=20),
               comment='Cryptocurrency (USDT, TON, BTC, etc.)',
               existing_comment='Cryptocurrency (USDT, TON, BTC, ETH, etc.)',
               existing_nullable=False)
    # ### end Alembic commands ###
