"""change_id_columns_from_bigint_to_int

Revision ID: 71f68a021d5a
Revises: 88ae85f1ab6d
Create Date: 2025-11-17 04:19:18.397053

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71f68a021d5a"
down_revision: Union[str, Sequence[str], None] = "88ae85f1ab6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admin_logs",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "admin_logs",
        "admin_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_comment="Admin telegram ID",
        existing_nullable=False,
    )
    op.alter_column(
        "admin_logs",
        "target_user_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_comment="Target user ID (if applicable)",
        existing_nullable=True,
    )
    op.alter_column(
        "chat_history",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "chat_history",
        "user_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_comment="User ID (foreign key)",
        existing_nullable=False,
    )
    op.alter_column(
        "cost_tracking",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "cost_tracking",
        "user_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_comment="User ID (foreign key)",
        existing_nullable=False,
    )
    op.alter_column(
        "request_limits",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "request_limits",
        "user_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_comment="User ID (foreign key)",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "request_limits",
        "user_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_comment="User ID (foreign key)",
        existing_nullable=False,
    )
    op.alter_column(
        "request_limits",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "cost_tracking",
        "user_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_comment="User ID (foreign key)",
        existing_nullable=False,
    )
    op.alter_column(
        "cost_tracking",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "chat_history",
        "user_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_comment="User ID (foreign key)",
        existing_nullable=False,
    )
    op.alter_column(
        "chat_history",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "admin_logs",
        "target_user_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_comment="Target user ID (if applicable)",
        existing_nullable=True,
    )
    op.alter_column(
        "admin_logs",
        "admin_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_comment="Admin telegram ID",
        existing_nullable=False,
    )
    op.alter_column(
        "admin_logs",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
