"""add_custom_daily_limit_to_users

Revision ID: 7dbcfcab758d
Revises: b04d220faa3d
Create Date: 2025-11-27 15:27:39.109571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dbcfcab758d'
down_revision: Union[str, Sequence[str], None] = 'b04d220faa3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_daily_limit', sa.Integer(), nullable=True, comment='Custom daily request limit set by admin (overrides tier limit)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'custom_daily_limit')
    # ### end Alembic commands ###
