"""Add historical prices, on-chain metrics, and funding rates tables

Revision ID: 897e74eec34d
Revises: 71f68a021d5a
Create Date: 2025-11-17 15:03:37.466353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897e74eec34d'
down_revision: Union[str, Sequence[str], None] = '71f68a021d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='Trading symbol (BTCUSDT, ETHUSDT, etc.)'),
    sa.Column('exchange', sa.String(length=50), nullable=False, comment='Exchange name (binance, bybit, etc.)'),
    sa.Column('funding_rate', sa.Float(), nullable=False, comment='Funding rate (e.g., 0.0001 = 0.01%)'),
    sa.Column('funding_time', sa.DateTime(), nullable=False, comment='Funding interval timestamp'),
    sa.Column('mark_price', sa.Float(), nullable=True, comment='Mark price at funding time'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', 'funding_time', name='uix_symbol_exchange_time')
    )
    op.create_index(op.f('ix_funding_rates_funding_time'), 'funding_rates', ['funding_time'], unique=False)
    op.create_index(op.f('ix_funding_rates_symbol'), 'funding_rates', ['symbol'], unique=False)
    op.create_table('historical_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False, comment='CoinGecko coin ID (bitcoin, ethereum, etc.)'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Candlestick timestamp'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='Timeframe: 1h, 4h, 1d, 1w'),
    sa.Column('open', sa.Float(), nullable=False, comment='Opening price'),
    sa.Column('high', sa.Float(), nullable=False, comment='Highest price'),
    sa.Column('low', sa.Float(), nullable=False, comment='Lowest price'),
    sa.Column('close', sa.Float(), nullable=False, comment='Closing price'),
    sa.Column('volume', sa.Float(), nullable=False, comment='Trading volume'),
    sa.Column('market_cap', sa.Float(), nullable=True, comment='Market capitalization'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_id', 'timestamp', 'timeframe', name='uix_coin_timestamp_timeframe')
    )
    op.create_index(op.f('ix_historical_prices_coin_id'), 'historical_prices', ['coin_id'], unique=False)
    op.create_index(op.f('ix_historical_prices_timestamp'), 'historical_prices', ['timestamp'], unique=False)
    op.create_table('onchain_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False, comment='Asset ID (btc, eth, sol, etc.)'),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment='Metric name (active_addresses, txn_count, etc.)'),
    sa.Column('value', sa.Float(), nullable=False, comment='Metric value'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Metric timestamp'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin_id', 'metric_name', 'timestamp', name='uix_coin_metric_timestamp')
    )
    op.create_index(op.f('ix_onchain_metrics_coin_id'), 'onchain_metrics', ['coin_id'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_metric_name'), 'onchain_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_timestamp'), 'onchain_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onchain_metrics_timestamp'), table_name='onchain_metrics')
    op.drop_index(op.f('ix_onchain_metrics_metric_name'), table_name='onchain_metrics')
    op.drop_index(op.f('ix_onchain_metrics_coin_id'), table_name='onchain_metrics')
    op.drop_table('onchain_metrics')
    op.drop_index(op.f('ix_historical_prices_timestamp'), table_name='historical_prices')
    op.drop_index(op.f('ix_historical_prices_coin_id'), table_name='historical_prices')
    op.drop_table('historical_prices')
    op.drop_index(op.f('ix_funding_rates_symbol'), table_name='funding_rates')
    op.drop_index(op.f('ix_funding_rates_funding_time'), table_name='funding_rates')
    op.drop_table('funding_rates')
    # ### end Alembic commands ###
