"""add_is_banned_to_users

Revision ID: b04d220faa3d
Revises: 630cbed7a5c1
Create Date: 2025-11-27 15:21:01.270558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04d220faa3d'
down_revision: Union[str, Sequence[str], None] = '630cbed7a5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=True, comment='Is user banned from using the bot'))
    # Set default value for existing rows
    op.execute("UPDATE users SET is_banned = FALSE WHERE is_banned IS NULL")
    # Make column NOT NULL
    op.alter_column('users', 'is_banned', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    # ### end Alembic commands ###
