"""add_fraud_detection_fingerprinting

Revision ID: c96a01e68035
Revises: e9044d387530
Create Date: 2025-11-28 22:38:20.004190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96a01e68035'
down_revision: Union[str, Sequence[str], None] = 'e9044d387530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: broadcast_templates and broadcast_logs already created in e1b2c3d4f5a6_add_broadcast_system.py
    op.create_table('device_fingerprints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='User ID (foreign key)'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='Client IP address'),
    sa.Column('ip_country', sa.String(length=100), nullable=True, comment='Country from IP geolocation'),
    sa.Column('ip_city', sa.String(length=100), nullable=True, comment='City from IP geolocation'),
    sa.Column('ip_asn', sa.String(length=255), nullable=True, comment='ASN/ISP info'),
    sa.Column('visitor_id', sa.String(length=100), nullable=True, comment='FingerprintJS visitor ID (persistent)'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='FingerprintJS request ID (single request)'),
    sa.Column('fingerprint_hash', sa.String(length=64), nullable=True, comment='Custom fingerprint hash (canvas, webgl, fonts)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Full user agent string'),
    sa.Column('platform', sa.String(length=20), nullable=False, comment='Platform: telegram, web, ios, android, miniapp'),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='Device type: desktop, mobile, tablet'),
    sa.Column('browser_name', sa.String(length=50), nullable=True, comment='Browser name: Chrome, Safari, Firefox'),
    sa.Column('os_name', sa.String(length=50), nullable=True, comment='OS name: Windows, macOS, iOS, Android'),
    sa.Column('telegram_device_model', sa.String(length=100), nullable=True, comment='Telegram device model (from initData)'),
    sa.Column('telegram_platform', sa.String(length=50), nullable=True, comment='Telegram platform (ios, android, tdesktop)'),
    sa.Column('telegram_version', sa.String(length=20), nullable=True, comment='Telegram app version'),
    sa.Column('screen_resolution', sa.String(length=20), nullable=True, comment='Screen resolution (1920x1080)'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='Browser timezone'),
    sa.Column('language', sa.String(length=20), nullable=True, comment='Browser language'),
    sa.Column('event_type', sa.String(length=30), nullable=False, comment='Event type: registration, login, payment, referral_use'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fingerprint creation timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_fingerprints_created_at'), 'device_fingerprints', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_fingerprint_hash'), 'device_fingerprints', ['fingerprint_hash'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_ip_address'), 'device_fingerprints', ['ip_address'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_platform'), 'device_fingerprints', ['platform'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_user_id'), 'device_fingerprints', ['user_id'], unique=False)
    op.create_index(op.f('ix_device_fingerprints_visitor_id'), 'device_fingerprints', ['visitor_id'], unique=False)
    op.create_table('linked_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_a', sa.Integer(), nullable=False, comment='First user ID (always smaller)'),
    sa.Column('user_id_b', sa.Integer(), nullable=False, comment='Second user ID (always larger)'),
    sa.Column('link_type', sa.String(length=30), nullable=False, comment='Link type: ip_match, fingerprint_match, device_match, self_referral, multi_trial'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Confidence score 0.0-1.0 (higher = more likely abuse)'),
    sa.Column('shared_ips', sa.Text(), nullable=True, comment='JSON array of shared IP addresses'),
    sa.Column('shared_fingerprints', sa.Text(), nullable=True, comment='JSON array of shared fingerprint hashes'),
    sa.Column('shared_visitor_ids', sa.Text(), nullable=True, comment='JSON array of shared FingerprintJS visitor IDs'),
    sa.Column('evidence_details', sa.Text(), nullable=True, comment='JSON with additional evidence details'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: detected, confirmed_abuse, false_positive, ignored'),
    sa.Column('trial_blocked', sa.Boolean(), nullable=False, comment='Trial was blocked due to this link'),
    sa.Column('referral_blocked', sa.Boolean(), nullable=False, comment='Referral bonus was blocked due to this link'),
    sa.Column('accounts_banned', sa.Boolean(), nullable=False, comment='Accounts were banned due to this link'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='When admin reviewed this link'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='Admin user ID who reviewed'),
    sa.Column('admin_notes', sa.Text(), nullable=True, comment='Admin notes about this link'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Link detection timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Last update timestamp'),
    sa.ForeignKeyConstraint(['user_id_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id_a', 'user_id_b', 'link_type', name='uq_linked_accounts')
    )
    op.create_index(op.f('ix_linked_accounts_created_at'), 'linked_accounts', ['created_at'], unique=False)
    op.create_index(op.f('ix_linked_accounts_link_type'), 'linked_accounts', ['link_type'], unique=False)
    op.create_index(op.f('ix_linked_accounts_status'), 'linked_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_linked_accounts_user_id_a'), 'linked_accounts', ['user_id_a'], unique=False)
    op.create_index(op.f('ix_linked_accounts_user_id_b'), 'linked_accounts', ['user_id_b'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linked_accounts_user_id_b'), table_name='linked_accounts')
    op.drop_index(op.f('ix_linked_accounts_user_id_a'), table_name='linked_accounts')
    op.drop_index(op.f('ix_linked_accounts_status'), table_name='linked_accounts')
    op.drop_index(op.f('ix_linked_accounts_link_type'), table_name='linked_accounts')
    op.drop_index(op.f('ix_linked_accounts_created_at'), table_name='linked_accounts')
    op.drop_table('linked_accounts')
    op.drop_index(op.f('ix_device_fingerprints_visitor_id'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_user_id'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_platform'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_ip_address'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_fingerprint_hash'), table_name='device_fingerprints')
    op.drop_index(op.f('ix_device_fingerprints_created_at'), table_name='device_fingerprints')
    op.drop_table('device_fingerprints')
    # NOTE: broadcast_templates and broadcast_logs managed by e1b2c3d4f5a6_add_broadcast_system.py
    # ### end Alembic commands ###
